# Generated by Django 5.2.6 on 2025-10-07 16:50
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_completo_modelos'),
    ]

    operations = [
        # Agregar campo correo_electronico al modelo Cliente existente
        migrations.AddField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(max_length=254, unique=True, default='temp@example.com'),
            preserve_default=False,
        ),
        
        # Agregar campo apellido al modelo Cliente existente
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=100, default=''),
            preserve_default=False,
        ),
    ]
