# Generated by Django 4.2.11 on 2025-10-30 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_agenda_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
    ]
