# Generated by Django 4.2.11 on 2025-11-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_cliente_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacion',
            name='estado',
        ),
        migrations.AddField(
            model_name='reparacion',
            name='condicion_vehiculo',
            field=models.CharField(choices=[('excelente', 'Excelente - Vehículo como nuevo, solo mantenimiento preventivo'), ('bueno', 'Bueno - Desgaste leve, puede necesitar ajustes menores'), ('regular', 'Regular - Desgaste notable, necesita reparaciones moderadas'), ('malo', 'Malo - Desgastado, necesita reparaciones extensas'), ('critico', 'Crítico - Daño estructural, posible pérdida total')], default='regular', help_text='Estado general del vehículo que determina el tipo de reparación necesaria', max_length=20, verbose_name='Condición del Vehículo'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='estado_reparacion',
            field=models.CharField(choices=[('pendiente', '🟡 Pendiente'), ('en_progreso', '🔵 En Progreso'), ('en_espera', '🟠 En Espera de Repuestos'), ('revision', '🟣 Lista para Revisión'), ('completada', '🟢 Completada'), ('cancelada', '🔴 Cancelada')], default='pendiente', help_text='Estado actual de la reparación', max_length=20, verbose_name='Estado de la Reparación'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre la reparación', null=True),
        ),
    ]
