# Generated by Django 4.2.11 on 2025-11-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_reparacion_mecanico_asignado'),
        ('gestion', '0007_tarea'),
    ]

    operations = [
    ]
