# Generated by Django 4.2.11 on 2025-11-12 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_remove_reparacion_mecanico_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='mecanico_asignado',
            field=models.ForeignKey(blank=True, help_text='Mecánico responsable de la reparación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones_asignadas', to='gestion.empleado', verbose_name='Mecánico Asignado'),
        ),
    ]
