# Generated by Django 4.2.11 on 2025-11-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_reparacion_mecanico_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='es_encargado',
            field=models.BooleanField(default=False, help_text='Usuario con permisos de encargado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='es_jefe',
            field=models.BooleanField(default=False, help_text='Usuario con permisos de jefe'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='es_mecanico',
            field=models.BooleanField(default=False, help_text='Usuario con permisos de mecánico'),
        ),
    ]
