# Generated by Django 4.2.11 on 2025-11-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_userprofile_es_encargado_userprofile_es_jefe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='vin',
            field=models.CharField(blank=True, help_text='Número de Identificación del Vehículo (17 caracteres)', max_length=17, null=True, verbose_name='VIN'),
        ),
    ]
