# Generated by Django 5.2.8 on 2025-11-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_vehiculo_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='fecha_programada',
            field=models.DateField(blank=True, help_text='Fecha en que el cliente llevará el vehículo al taller', null=True, verbose_name='Fecha Programada'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='hora_programada',
            field=models.TimeField(blank=True, help_text='Hora en que el cliente llevará el vehículo al taller', null=True, verbose_name='Hora Programada'),
        ),
    ]
